### ISSUE TITLE
TypeError exception

### ISSUE THREAD

**Issue by vitalyk-multinarity** [usefulness/diffuse-action#63]
I tried to use this action for comparison two CSVs, unfortunately it fails. I tried both with the default diffuse-repo and with JakeWharton's one.
Please suggest.
TIA,
Vitaly

```
- id: diffuse
        uses: usefulness/diffuse-action@v1
        with:
          old-file-path: file1.csv
          new-file-path: file2.csv
          diffuse-repo: JakeWharton/diffuse
          lib-version: 0.1.0
```

```
Traceback (most recent call last):
  File "/home/runner/work/_actions/usefulness/diffuse-action/v1/entrypoint.py", line 139, in <module>
    print(" ".join(java_call))
TypeError: sequence item 4: expected str instance, NoneType found

```

**Comment by mateuszkwiecinski** [comment]
Diffuse tool doesn't support `csv` files 👀 Your input fails at finding supported extension to pass to diffuse tool: https://github.com/usefulness/diffuse-action/blob/d816fd102c1f5f69519ee4bb8e0e12a42d005788/entrypoint.py#L119

As Diffuse's readme says: 
>Diffuse is a tool for diffing APKs, AABs, AARs, and JARs in a way that aims to provide both a high-level view of what changes along with important detailed output.

so only apks, aabs, aars, and jars produced during Android project builds are supported 👀

**Comment by vitalyk-multinarity** [comment]
> Diffuse tool doesn't support `csv` files 👀 Your input fails at finding supported extension to pass to diffuse tool:
> 
> https://github.com/usefulness/diffuse-action/blob/d816fd102c1f5f69519ee4bb8e0e12a42d005788/entrypoint.py#L119
> 
> As Diffuse's readme says:
> 
> > Diffuse is a tool for diffing APKs, AABs, AARs, and JARs in a way that aims to provide both a high-level view of what changes along with important detailed output.
> 
> so only apks, aabs, aars, and jars produced during Android project builds are supported 👀

Thank you! I guess I confused with https://github.com/MightyCreak/diffuse.

**Comment by mateuszkwiecinski** [comment]
Huh, interesting 👀 I can only link: https://github.com/JakeWharton/diffuse/issues/108 as _related_
Thanks for sharing the link!
